### ISSUE TITLE
用vs编译报了上千个错误

### ISSUE THREAD

**Issue by xumingxiang** [alibaba/tblive#2]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2065	“Archive”: 未声明的标识符	tblive	d:\workstudio\tblive-master\tblive\deps\peregrine\include\base\srlz\srlz_base.h	75	
错误	C2059	语法错误:“const”	tblive	d:\workstudio\tblive-master\tblive\deps\peregrine\include\base\srlz\srlz_base.h	75	
错误	C2143	语法错误: 缺少“;”(在“{”的前面)	tblive	d:\workstudio\tblive-master\tblive\deps\peregrine\include\base\srlz\srlz_base.h	76	
错误	C2447	“{”: 缺少函数标题(是否是老式的形式表?)	tblive	d:\workstudio\tblive-master\tblive\deps\peregrine\include\base\srlz\srlz_base.h	76	
错误	C2059	语法错误:“{”	tblive	d:\workstudio\tblive-master\tblive\deps\peregrine\include\base\srlz\srlz_base.h	94	
错误	C2334	“{”的前面有意外标记；跳过明显的函数体	tblive	d:\workstudio\tblive-master\tblive\deps\peregrine\include\base\srlz\srlz_base.h	94	
错误	C4430	缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int	tblive	d:\workstudio\tblive-master\tblive\deps\peregrine\include\base\srlz\srlz_base.h	100	
错误	C2988	不可识别的模板声明/定义	tblive	d:\workstudio\tblive-master\tblive\deps\peregrine\include\base\srlz\srlz_base.h	100	
错误	C2143	语法错误: 缺少“;”(在“&”的前面)	tblive	d:\workstudio\tblive-master\tblive\deps\peregrine\include\base\srlz\srlz_base.h	100	
错误	C2433	“Archive”: 不允许在数据声明中使用“inline”	tblive	d:\workstudio\tblive-master\tblive\deps\peregrine\include\base\srlz\srlz_base.h	100	
错误	C2238	意外的标记位于“;”之前	tblive	d:\workstudio\tblive-master\tblive\deps\peregrine\include\base\srlz\srlz_base.h	100	
错误	C2059	语法错误:“&”	tblive	d:\workstudio\tblive-master\tblive\deps\peregrine\include\base\srlz\srlz_base.h	100	
错误	C2334	“{”的前面有意外标记；跳过明显的函数体	tblive	d:\workstudio\tblive-master\tblive\deps\peregrine\include\base\srlz\srlz_base.h	109	
错误	C2988	不可识别的模板声明/定义	tblive	d:\workstudio\tblive-master\tblive\deps\peregrine\include\base\srlz\srlz_base.h	117	
错误	C2059	语法错误:“{”	tblive	d:\workstudio\tblive-master\tblive\deps\peregrine\include\base\srlz\srlz_base.h	117	
错误	C2334	“{”的前面有意外标记；跳过明显的函数体	tblive	d:\workstudio\tblive-master\tblive\deps\peregrine\include\base\srlz\srlz_base.h	117	
错误	C2977	“srlz::member_nvio”: 模板 参数太多	tblive	d:\workstudio\tblive-master\tblive\deps\peregrine\include\base\srlz\srlz_member.h	24	
错误	C2143	语法错误: 缺少“,”(在“<”的前面)	tblive	d:\workstudio\tblive-master\tblive\deps\peregrine\include\base\srlz\srlz_member.h	132	
错误	C2977	“srlz::member_nvio”: 模板 参数太多	tblive	d:\workstudio\tblive-master\tblive\deps\peregrine\include\base\srlz\srlz_member.h	137	
错误	C2977	“srlz::member_nvio”: 模板 参数太多	tblive	d:\workstudio\tblive-master\tblive\deps\peregrine\include\base\srlz\srlz_member.h	143	
错误	C2143	语法错误: 缺少“,”(在“<”的前面)	tblive	d:\workstudio\tblive-master\tblive\deps\peregrine\include\base\srlz\srlz_member.h	147	
错误	C2977	“srlz::member_nvio”: 模板 参数太多	tblive	d:\workstudio\tblive-master\tblive\deps\peregrine\include\base\srlz\srlz_member.h	152	
错误	C2977	“srlz::member_nvio”: 模板 参数太多	tblive	d:\workstudio\tblive-master\tblive\deps\peregrine\include\base\srlz\srlz_member.h	177

**Comment by xumingxiang** [comment]
已解决！
1：把报错的文件重新保存为utf-8带签名
2：添加预处理器定义 _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS=1
3：使用RelWithDebInfo模式编译

**Comment by nickwwww** [comment]
请问大家编译的时候都没有遇到C语言变量声明在语句块中的问题么？
