### ISSUE TITLE
请问阿里大神如果在64位机器上编译通过

### ISSUE THREAD

**Issue by wujiangxu-agent** [alibaba/tblive#4]
阿里的大神
你们好

我目前按照README编译安装tblive，但是最后一步提示错误
Error	26	error LNK1112: module machine type 'X86' conflicts with target machine type 'x64'	D:\code\tblive-master\output\obs\base.lib(base.dll)	tblive
我理解这个是因为我机器使64位，但是编译环境有些地方设置了32位了，我查看并修改了看了cmakelist的一些地方

if(WIN32)
	set(DepsPath    "${CMAKE_SOURCE_DIR}/third_party/win64/include")
	set(FFmpegPath  "${CMAKE_SOURCE_DIR}/third_party/win64/include")
	set(x264Path    "${CMAKE_SOURCE_DIR}/third_party/win64/include")
	set(curlPath    "${CMAKE_SOURCE_DIR}/third_party/win64/include")
	set(PrgPath    "${CMAKE_SOURCE_DIR}/deps/peregrine/Win32")
	set(AuthSDKPath    "${CMAKE_SOURCE_DIR}/deps/AuthSDK/AliAuthSDK/pack/bin/win32")
	set(D3DPath    "${CMAKE_SOURCE_DIR}/deps/d3d/win32")

上面的third_party部分我修改了一些win64,但是PrgPath， AuthSDKPath，D3DPath 怎么设置64位呢？？
上面提示base.dll  是如何生成的，怎么修改生成64位的库呢？？

请大神指教!!

**Comment by suninf** [comment]
你好，工程默认编译目标就是32位的哦，和本机64位没有关系

```
@set build_type="RelWithDebInfo|Win32"
@if {%debug_type%} == {1} (set build_type="Debug|Win32")
```

**Comment by nickwwww** [comment]
大神
感谢回复：

使用win32的原因是考虑兼容性么？
我使用obs_win_build.bat后面应该带参数么？我就执行了obs_win_build.bat 后就报错

**Comment by nickwwww** [comment]
![image](https://cloud.githubusercontent.com/assets/8360784/23595532/8fdd96f4-025d-11e7-89c4-dcf1d228bc7e.png)

**Comment by nickwwww** [comment]
我知道刚才的错误了，在CMake选择vs2013的时候，我还是选择了64位的版本这个导致了错误。
我刚才又按照readme重新做了一遍，在CMake选择2013的时候，我选择了32位的版本。
但是还是有编译错误，错误分为两种类型
1） link 错误
Error	325	error LNK1104: cannot open file '..\libobs\Debug\obs.lib'	D:\code\tblive-master\build\libobs-opengl\LINK	libobs-opengl
Error	326	error LNK1104: cannot open file '..\libobs\Debug\obs.lib'	D:\code\tblive-master\build\libobs-d3d11\LINK	libobs-d3d11
Error	355	error LNK1104: cannot open file '..\libobs\Debug\obs.lib'	D:\code\tblive-master\build\obs\LINK	tblive
Error	299	error LNK1104: cannot open file '..\..\libobs\Debug\obs.lib'	D:\code\tblive-master\build\plugins\coreaudio-encoder\LINK	coreaudio-encoder
Error	300	error LNK1104: cannot open file '..\..\libobs\Debug\obs.lib'	D:\code\tblive-master\build\plugins\win-wasapi\LINK	win-wasapi
Error	301	error LNK1104: cannot open file '..\..\libobs\Debug\obs.lib'	D:\code\tblive-master\build\plugins\win-mf\LINK	win-mf
Error	324	error LNK1104: cannot open file '..\..\libobs\Debug\obs.lib'	D:\code\tblive-master\build\plugins\obs-filters\LINK	obs-filters
Error	327	error LNK1104: cannot open file '..\..\libobs\Debug\obs.lib'	D:\code\tblive-master\build\plugins\obs-transitions\LINK	obs-transitions
Error	328	error LNK1104: cannot open file '..\..\libobs\Debug\obs.lib'	D:\code\tblive-master\build\plugins\rtmp-services\LINK	rtmp-services
Error	329	error LNK1104: cannot open file '..\..\libobs\Debug\obs.lib'	D:\code\tblive-master\build\plugins\text-freetype2\LINK	text-freetype2
Error	330	error LNK1104: cannot open file '..\..\libobs\Debug\obs.lib'	D:\code\tblive-master\build\plugins\win-capture\LINK	win-capture
Error	332	error LNK1104: cannot open file '..\..\libobs\Debug\obs.lib'	D:\code\tblive-master\build\plugins\win-dshow\LINK	win-dshow
Error	331	error LNK1104: cannot open file '..\..\..\libobs\Debug\obs.lib'	D:\code\tblive-master\build\plugins\decklink\win\LINK	win-decklink
 我发现libobs/Debug/obs.lib 是空的
![image](https://cloud.githubusercontent.com/assets/8360784/23596706/0ee4f96a-0268-11e7-9af2-2f4c6ccc9f97.png)

2） 第二个错误是很多C语言的变量生命在语句的后面，导致报错，不知道你们这里是如何处理的


感谢并期待大神的回复

**Comment by wujiangxu-agent** [comment]
感谢大神的回复，我在看看啊

**Comment by wujiangxu-agent** [comment]
经过几天的折腾，终于可以运行了，总结一下遇到的各种问题
1) 本开源代码是选择的是32位编译模式，所以在CMake选择vs2013的版本时候，一定要选择非64位
2) 要选择Vs2013 update4以上版本，因为这个版本才支持C99的编译，这个就支持C语言变量定义在语句中，否则只是C89的编译标准，会出现很多错误

感谢suninf给予的帮助了，新手很多低级错误，谢谢你的指导
